### ISSUE TITLE
User role 부여, 체크 구현

### ISSUE THREAD

**Issue by Dh3356** [mju-likelion/hackathon-team3-server#116]
## Description
User role 부여, 체크 구현

## Changes
- [x] jwt 경로 리팩터링
- [x] userEntity에 role 컬럼 추가
- [x] RoleGuard, Role 데코레이터 구현(JwtAuthGuard를 통해 넘겨받은 유저의 권한이 @Role데코레이터 안에 있는 값과 같은지 RoleGuard에서 검사
- [x] Role -> JwtAuthGuard -> RoleGuard 순서로 통과하게 하나로 합쳐서 @Auth 데코레이터로
- [x] Auth 데코레이터 모든 엔드포인트에 적용, 임시로 Role를 ANY로

## Additional context

**Comment by Dh3356** [comment]
@hou27 @ndaemy 코드리뷰 해 주시면 감사하겠습니다!

**Comment by hou27** [comment]
pr로 올려주실 수 있을까요? 또 pr 생성하실 때 정보를 지금보다 쪼금만 더 주시면 어느 부분을 봐야할 지 판단하기 좋을 것 같아요 :)

**Comment by Dh3356** [comment]
네!
