### ISSUE TITLE
초기 Entity 작성

### ISSUE THREAD

**Issue by Dh3356** [mju-likelion/hackathon-team3-server#2]
## Description
초기 Entity 작성
### Entity 작업
- [x] userEntity
- [x] learningEntity
- [x] chapterEntity
- [x] problemEntity

### DB Connection 작업
- [x] typeORM, MySQL
## Additional context
- 변경될 수 있는 내용, branch 분기 전 진행하는 공통 작업

**Comment by hou27** [comment]
### Problem Entity
- content: 문제와 문제에 필요한 정보를 담고 있음
    case 1: 객관식
    "문제:멋쟁이 사자처럼의 대표 색깔은?보기:검정색,노란색,파란색,빨간색"
    case 2: 주관식
    "문제:멋쟁이 사자처럼의 대표 색깔은?"
    case 3: 빈칸
    "문제:멋쟁이 사자처럼의 대표 색깔은 @@@이다."
- type: 문제의 종류(enum으로 처리)
    객관식 - MCQ (Multiple Choice Question)
    주관식 - SAQ (Short Answer Question)
    빈칸채우기 - FITB (Fill in the Blank)
