### ISSUE TITLE
answerOptions 컬럼 추가, 이에 따른 코드 변경

### ISSUE THREAD

**Issue by hou27** [mju-likelion/hackathon-team3-server#34]
## Description
problem.entity에 answerOptions 컬럼 추가, 이에 따른 코드 변경

## Changes
- [x] answerOptions 컬럼 추가
- [x] 코드 변경

## Additional context
- 타입이 MCQ(객관식)인 problem만 값을 가지고, 타입이  MCQ(객관식)가 아닌 problem은 NULL

형식
- 객관식 보기가 "검은색", "빨간색", "초록색" 이라면 
- answerOptions는 "검은색,빨간색,초록색" <- ',' 를 기준으로 split하여 사용할 것

**Comment by Dh3356** [comment]
@hou27 
answerOptions가 생겨남에 따라 problem.util 의 필요성이 줄어들었다고 생각해 주석 처리 해 뒀습니다. 


- “문제:멋쟁이 사자처럼의 대표 색깔은?보기:검정색,노란색,파란색,빨간색" 에서 answerOptions가 생겨남에 따라 
- content에는 "멋쟁이 사자처럼의 대표 색깔은?" 만 저장하고
- answerOptions에 "검정색,노란색,파란색,빨간색"을 저장합니다.

이에 따라 기존 content에서 쓰던 형식이 사라지고, problem.util 의 필요성이 줄어들었다고 생각했습니다!

**Comment by hou27** [comment]
> @hou27 
> 
> answerOptions가 생겨남에 따라 problem.util 의 필요성이 줄어들었다고 생각해 주석 처리 해 뒀습니다. 
> 
> 
> 
> 
> 
> - “문제:멋쟁이 사자처럼의 대표 색깔은?보기:검정색,노란색,파란색,빨간색" 에서 answerOptions가 생겨남에 따라 
> 
> - content에는 "멋쟁이 사자처럼의 대표 색깔은?" 만 저장하고
> 
> - answerOptions에 "검정색,노란색,파란색,빨간색"을 저장합니다.
> 
> 
> 
> 이에 따라 기존 content에서 쓰던 형식이 사라지고, problem.util 의 필요성이 줄어들었다고 생각했습니다!
> 
> 결정되면 entity 주석 수정, service 주석 수정 하겠습니다~

따봉입니다
