### ISSUE TITLE
로그인, 회원가입 기능 구현

### ISSUE THREAD

**Issue by Dh3356** [mju-likelion/hackathon-team3-server#4]
로그인, 회원가입 기능 구현

- [x] 기능 구현을 위한 usersService 구현
- [x] 회원가입 기능 구현
- [x] 로그인 기능 구현

**Comment by Dh3356** [comment]
.env 이슈로 인해 테스트는 진행하지 못한 상황으로, 해결되는 대로 테스트 진행하고 수정 사항 반영 예정.

**Comment by hou27** [comment]
1. findOne method 덜어내기
2. dto 네이밍 변경
3. NODE_ENV는 env file에 불필요
4. 말씀하신 상황 확인 결과 저는 잘 동작합니당

**Comment by hou27** [comment]
@Dh3356 
<img width="817" alt="image" src="https://github.com/mju-likelion/hackathon-team3-server/assets/65845941/2605ee0e-8a77-4f5b-9dd8-54a664fc3582">
저는 잘 동작해요! 어떤 부분이 문제였는지 공유해주시면 감사하겠습니다.
그리고 현재 password validation 동작하지 않습니다. 
```
app.useGlobalPipes(new ValidationPipe());
```
위 코드 main에 추가하셔야해요

**Comment by Dh3356** [comment]
반영하겠습니다

**Comment by Dh3356** [comment]
commit ID: bd79b8d은 무시하시면 됩니다

**Comment by hou27** [comment]
> commit ID: bd79b8d은 무시하시면 됩니다

넴

**Comment by Dh3356** [comment]
현재 로그인 기능 수정 중 userEntity의 password 컬럼이 select: false로 되어 있어 userEntity의 checkPassword 함수의 this.password가 undefined로 나오고 있는 상황입니다.  select: false를 삭제하는 게 좋을까요?

**Comment by hou27** [comment]
> 현재 로그인 기능 수정 중 userEntity의 password 컬럼이 select: false로 되어 있어 userEntity의 checkPassword 함수의 this.password가 undefined로 나오고 있는 상황입니다. select: false를 삭제하는 게 좋을까요?
select을 통해 password를 가져올 수 있습니다.
`select: { id: true, password: true },`

물론 이렇게 안 하고 말씀하신 것처럼 select: false를 삭제해서 해결할 수 있겠네요!
해당 옵션을 부여했던 건 의도치 않게 민감한 password의 데이터를 꺼내는 경우를 방지해뒀던 건데
어떻게 하는 게 좋을까요?

**Comment by Dh3356** [comment]
select: false를 삭제하는 건 좋지 않다고 생각하고 있습니다. 

`select: { id: true, password: true }`
를 어디에 삽입한다는 말씀이신가요??

**Comment by hou27** [comment]
@Dh3356 
예시 코드입니다!  
```ts
const user = await queryRunnerManager.findOne(User, {
  where: { id: userId },
  select: { id: true, password: true },
});
```

**Comment by Dh3356** [comment]
해결했습니다 ^^
