### ISSUE TITLE
Rate Limiting이 전체 controller에 적용되는 현상 수정

### ISSUE THREAD

**Issue by Dh3356** [mju-likelion/hackathon-team3-server#55]
## Description
Rate Limiting이 전체 controller에 적용되는 현상 수정

## Changes
- [x] problemsController의 submitProblem()에만 적용되도록 수정
## Additional context

**Comment by Dh3356** [comment]
@hou27 
throttler가 controller에 적용하는 데코레이터라는 것을 알게 되었는데...
이렇게 되면 모든 채점 요청에 대해(주관식 포함) Rate Limiting을 해야 하는 상황입니다.
어떻게 하는 게 좋을까요? 우선 제가 생각해 본 것은 다음과 같습니다.

1. 모든 채점 요청에 대해 제한한다.
2. API를 객관식 채점 요청, 주관식,빈칸 채점 요청 두 개로 나눈다.
3. 어떻게든 service에서 throttler를 다루는 방법을 찾아서 주관식이 아닐 떄만 Rate limiting이 되게 한다.

2번은 적절하지 않은 것 같고... 3번은 지금 계속 검색중인데 도통 나오지 않고 있습니다.

**Comment by hou27** [comment]
https://github.com/mju-likelion/hackathon-team3-server/blob/95ef88f74c83ea4e30e58554ccabf1ba39953fd4/src/problems/problems.service.ts#L80C12-L80C12  

별개로 이건 방금 발견한건데 여기 409 에러는 적절하지 않은 것 같습니다!  
외부 api 문제로 에러를 반환하는 의도라면 503 또는 사용자가 요청을 잘못해서 발생한 에러라면 400은 어떨까요?

**Comment by hou27** [comment]
> 

그럼 
```ts
@UseGuards(ThrottlerBehindProxyGuard)
```
이 코드가 
![image](https://github.com/mju-likelion/hackathon-team3-server/assets/65845941/53bbe6a0-938e-4b43-9447-f7e45842b9e3)
  
여기에 붙는 거죠?

**Comment by Dh3356** [comment]
네 맞습니다 1번으로 수정한다면 이렇게 됩니다
![image](https://github.com/mju-likelion/hackathon-team3-server/assets/113977176/2668ab90-eed9-47be-9573-7e4d580df2c4)

**Comment by Dh3356** [comment]
에러코드도 수정해놓을게요!

**Comment by Dh3356** [comment]
그리고 지금 계속 찾아보다가 알아낸 사실인데 throller를 service 레이어에서 사용하는 것은 일반적으로 권장되는 사항이 아니라고 하네요

**Comment by hou27** [comment]
ThrottlerBehindProxyGuard에서 req.body를 확인해서 분기처리하는 건 어때요?

**Comment by hou27** [comment]
3번은 지금 guard를 사용하는 상황이라 불가능하고,  
2번 또는 제가 앞서 말씀드린 방법을 생각해봤는데,  
ThrottlerBehindProxyGuard가 하는 역할에 적합하지 않은 로직이 추가되는 것 같아서 좀 꺼려지구요,  
어차피 요청 속도를 제한하는거라 객관식도 함께 그냥 적용되어도 괜찮지 않을까하는 생각이 듭니다.  

물론 api 자체를 분리할 수 있겠지만 필요성을 못 느껴서요

**Comment by Dh3356** [comment]
좋은 생각이십니다. 그럼 1번으로 갈게요!
